In [6]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [8]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

b=np.array([[10,20,30],[40,50,60]])
c=np.array(a+b)
print(c)

[[11 22 33]
 [44 55 66]]


In [11]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [12]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([8,9,10])
print(np.vstack((a1,a2,a3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [13]:
a1=np.random.normal(1,0.5,10)
print(a1)

[1.38219993 1.15137482 0.66166788 1.83136191 1.50383335 0.52405843
 1.10447837 1.1741941  0.65386978 1.3984246 ]


In [20]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,10])
print(np.diagonal((a1,a2,a3)))
print(np.trace((a1,a2,a3)))

[ 1  5 10]
16


In [22]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [23]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [24]:
np.arange(1,2048,564)
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [25]:
  a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [26]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,2])

slicing column : [3 6]


In [28]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [31]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [35]:
a1=np.random.normal(1,5,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median Value=",np.median(a1))

[-12.05137799   6.41786841  -0.51733816  -0.36493819  -3.91518762
  -5.99109622   7.80159583  -3.47730539   5.30742718  -5.35595196]
Min value= -12.051377988092185
Max value= 7.801595826439608
Mean value= -1.2146304116784177
Median Value= -1.9973217758358297


In [36]:
a1=np.array(([1,2],[3,4]))
a2=np.array(([5,6],[6,7]))
print(np.dot(a1,a2))

[[17 20]
 [39 46]]


In [40]:
import pandas as pd
dict={"Name":["Sandeep","Sai","Ram","Charan"],
      "Email ID":["sandeep@gmail.com","Sai@gmail.com","Ram@gmail.com","charan@gmail.com"],
      "Mobile Number":["9010012954","8341990008","9490725729","9652490969"],
      "Address":["Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

      Name           Email ID Mobile Number Address
0  Sandeep  sandeep@gmail.com    9010012954     Hyd
1      Sai      Sai@gmail.com    8341990008     Hyd
2      Ram      Ram@gmail.com    9490725729     Hyd
3   Charan   charan@gmail.com    9652490969     Hyd
